namespace: default

replicaCount: 1

image:
  repository: samjsui/heightful-backend-gateway
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: dev-heightful-registry

service:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080

resources:
  requests:
    memory: "256Mi"
  limits:
    memory: "512Mi"

environment:
  variables:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

spring:
  config:
    import: http://heightful-backend-config:8888/

heightful:
  service:
    auth:
      url: heightful-backend-auth.svc.cluster.local
    identity:
      url: heightful-backend-identity.svc.cluster.local

gateway:
  name: heightful-gateway
  className: nginx

route:
  name: heightful-gateway-route
  path: /
  hostname: localhost

certificate:
  issuer:
    key: issuer-account-key
  secret: heightful-gateway-tls