apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: {{ .Values.gateway.className | default "nginx" }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    hostname: "dev.api.heightful.com"
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.certificate.secret }}
        namespace: {{ .Release.Namespace }}
        kind: Secret