name: Deploy to Cluster (dev)

on:
  workflow_dispatch:
    inputs:
      heightful-backend-config:
        description: "heightful-backend-config Docker image tag"
        required: true
        default: "latest"
      heightful-backend-auth:
        description: "heightful-backend-auth Docker image tag"
        required: true
        default: "latest"
      heightful-backend-identity:
        description: "heightful-backend-identity Docker image tag"
        required: true
        default: "latest"
      heightful-backend-gateway:
        description: "heightful-backend-gateway Docker image tag"
        required: true
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_NAMESPACE: samjsui
      HEIGHTFUL_BACKEND_CONFIG_NAME: heightful-backend-config
      HEIGHTFUL_BACKEND_AUTH_NAME: heightful-backend-auth
      HEIGHTFUL_BACKEND_IDENTITY_NAME: heightful-backend-identity
      HEIGHTFUL_BACKEND_GATEWAY_NAME: heightful-backend-gateway

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig and setup Kubernetes context
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_CREDENTIALS_DEV }}
          kubectl config current-context

      - name: Determine Kubernetes namespace name
        id: determine_namespace
        run: echo "K8S_NAMESPACE=dev" >> $GITHUB_ENV

      - name: Clean up Service Namespace
        run: |
          if kubectl get namespace $K8S_NAMESPACE; then
            kubectl delete all --all -n $K8S_NAMESPACE
            kubectl delete configmaps --all -n $K8S_NAMESPACE
            kubectl delete secrets --all -n $K8S_NAMESPACE
          else
            echo "Namespace $K8S_NAMESPACE does not exist, skipping cleanup."
          fi

      - name: Create Docker Registry Secret
        run: |
          kubectl create secret docker-registry dev-heightful-registry \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email=${{ secrets.DOCKERHUB_EMAIL }} \
            -n $K8S_NAMESPACE || echo "Secret already exists"

      - name: Install NGINX Gateway Fabric
        run: |
          kubectl kustomize "https://github.com/nginxinc/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.4.0" | kubectl apply -f -

      - name: Deploy NGINX Gateway Fabric
        run: |
          kubectl apply -f https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/v1.4.0/deploy/default/deploy.yaml

      - name: Add Bitnami Helm Repository
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Deploy RabbitMQ
        run: |
          helm upgrade --install rabbitmq bitnami/rabbitmq \
            --set auth.username=${{ secrets.RABBITMQ_USERNAME }} \
            --set auth.password=${{ secrets.RABBITMQ_PASSWORD }} \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Deploy Config Service (heightful-backend-config)
        run: |
          helm upgrade --install $HEIGHTFUL_BACKEND_CONFIG_NAME ./charts/$HEIGHTFUL_BACKEND_CONFIG_NAME \
            --set image.tag=${{ github.event.inputs.heightful-backend-config }} \
            --set namespace=$K8S_NAMESPACE \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Deploy Auth Service (heightful-backend-auth)
        run: |
          helm upgrade --install $HEIGHTFUL_BACKEND_AUTH_NAME ./charts/$HEIGHTFUL_BACKEND_AUTH_NAME \
            --set image.tag=${{ github.event.inputs.heightful-backend-auth }} \
            --set namespace=$K8S_NAMESPACE \
            --set spring.config.import=http://heightful-backend-config.$K8S_NAMESPACE.svc.cluster.local:8888/ \
            --set rabbitmq.host=rabbitmq.$K8S_NAMESPACE.svc.cluster.local \
            --set rabbitmq.port=5672 \
            --set rabbitmq.username=${{ secrets.RABBITMQ_USERNAME }} \
            --set rabbitmq.password=${{ secrets.RABBITMQ_PASSWORD }} \
            --set auth.jwtSecret=${{ secrets.AUTH_JWT_SECRET }} \
            --set db.host=${{ secrets.DB_HOST }} \
            --set db.port=25060 \
            --set db.name=auth_dev \
            --set db.username=${{ secrets.DB_USERNAME }} \
            --set db.password=${{ secrets.DB_PASSWORD }} \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Deploy Identity Service (heightful-backend-identity)
        run: |
          helm upgrade --install $HEIGHTFUL_BACKEND_IDENTITY_NAME ./charts/$HEIGHTFUL_BACKEND_IDENTITY_NAME \
            --set image.tag=${{ github.event.inputs.heightful-backend-identity }} \
            --set namespace=$K8S_NAMESPACE \
            --set spring.config.import=http://heightful-backend-config.$K8S_NAMESPACE.svc.cluster.local:8888/ \
            --set rabbitmq.host=rabbitmq.$K8S_NAMESPACE.svc.cluster.local \
            --set rabbitmq.port=5672 \
            --set rabbitmq.username=${{ secrets.RABBITMQ_USERNAME }} \
            --set rabbitmq.password=${{ secrets.RABBITMQ_PASSWORD }} \
            --set db.host=${{ secrets.DB_HOST }} \
            --set db.port=25060 \
            --set db.name=identity_dev \
            --set db.username=${{ secrets.DB_USERNAME }} \
            --set db.password=${{ secrets.DB_PASSWORD }} \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Deploy Gateway Service (heightful-backend-gateway)
        run: |
          helm upgrade --install $HEIGHTFUL_BACKEND_GATEWAY_NAME ./charts/$HEIGHTFUL_BACKEND_GATEWAY_NAME \
            --set image.tag=${{ github.event.inputs.heightful-backend-gateway }} \
            --set namespace=$K8S_NAMESPACE \
            --set spring.config.import=http://heightful-backend-config.$K8S_NAMESPACE.svc.cluster.local:8888/ \
            --set route.hostname=dev.api.heightful.com \
            --set heightful.service.auth.url=http://heightful-backend-auth.$K8S_NAMESPACE.svc.cluster.local:8081/ \
            --set heightful.service.identity.url=http://heightful-backend-identity.$K8S_NAMESPACE.svc.cluster.local:8082/ \
            --namespace $K8S_NAMESPACE --create-namespace

      - name: Verify deployments
        run: |
          kubectl get pods -n $K8S_NAMESPACE
